### ISSUE TITLE
[Bug] Video upload does not seem to work "There was a problem with the media ID submitted with the Tweet."

### ISSUE THREAD

**Issue by MrPowerGamerBR** [StarryBlueSky/Penicillin#34]
**Bug Type / Bug の種類:**
- [ ] Uncaught exceptions / キャッチされていない例外
- [ ] Related to Model Class / モデルクラス関連
- [X] Others / その他

**Description / 概要:**  
Trying to send a tweet with a MP4 media does not seem to work, Twitter rejects the status update with `There was a problem with the media ID submitted with the Tweet.`

**Example Codes To Reproduce / Bug 再現コード:**  

I'm trying to upload [this video](https://cdn.discordapp.com/attachments/513405772911345664/838046102984196186/attack_on_heart.mp4), the video uploads fine with Twitter's Web Client.

I'm uploading the media with
```kotlin
val type = MediaType.MP4
val category = MediaCategory.TweetVideo
val data = byte array of the video

client.media.uploadMedia(
    MediaComponent(
        data,
        type,
        category
    )
).execute()
```

**Expected Behavior / 期待された結果:**  
The tweet would've been posted without any issues.

**Environment / 環境:**  
Please complete the following information to specify the problem.  
問題を特定するために以下の情報を埋めてください。  

 - OS: Windows 10 Pro 64 bits
 - Java Version: Java 15
 - Penicillin Version: 6.1.0
 - Kotlin Version: 1.4.32
 - Twitter Application: A third-party app with read & write permissions

**Additional context / 備考:**  
I tried using Ktor Logging to see what is the request that is being made to try to figure out the issue, but Ktor's Logging feature gets stuck due to the Tweetstorm request (which it is a Ktor Logging bug, because even if you filter the request it doesn't work)

**Comment by SlashNephy** [comment]
Thanks for the report.

After uploading media to Twitter, you actually need to wait for the media to be processed. (This is not a problem for images, but for videos it can take a few seconds.

After running the media upload endpoint, you need to make sure that the media has been processed before posting the tweet. For its implementation, please see https://github.com/StarryBlueSky/Penicillin/blob/dev/src/commonMain/kotlin/blue/starry/penicillin/extensions/endpoints/CreateTweetWithMedia.kt extension.

All you have to do is replace it with an extension function as follows.

```kotlin
import blue.starry.penicillin.extensions.endpoints.createWithMedia

val type = MediaType.MP4
val category = MediaCategory.TweetVideo
val data = `byte array of the video`

client.statuses.createWithMedia(
    builder.toString(),
    media = listOf(
        MediaComponent(
            data,
            type,
            category
        )
    )
).execute()
```

Please give it a try. We apologize for any inconvenience caused by the lack of documentation.

**Comment by MrPowerGamerBR** [comment]
Thank you, it worked! 🎉 

However I had issues with
```
java.lang.NoSuchMethodError: 'java.lang.Object kotlinx.coroutines.TimeoutKt.withTimeout-lwyi7ZQ(double, kotlin.jvm.functions.Function2, kotlin.coroutines.Continuation)'
	at blue.starry.penicillin.extensions.endpoints.CreateTweetWithMediaKt.awaitProcessing-Kx4hsE0(CreateTweetWithMedia.kt:84)
	at blue.starry.penicillin.extensions.endpoints.CreateTweetWithMediaKt.awaitProcessing-Kx4hsE0$default(CreateTweetWithMedia.kt:76)
	at blue.starry.penicillin.extensions.endpoints.CreateTweetWithMediaKt$createWithMedia$1.invokeSuspend(CreateTweetWithMedia.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.perfectdreams.loritta.platform.twitter.LorittaTwitter.start(LorittaTwitter.kt:154)
	at net.perfectdreams.loritta.platform.twitter.LorittaTwitterLauncher.main(LorittaTwitterLauncher.kt:21)
```

But I think that's just dependency version incompatibilies (even tho I didn't find almost any differences between Penicillin's versions dependencies and my project dependencies, just that I'm using newer versions for Kotlin/Ktor/Kotlin Coroutines, etc)

But that wasn't a huge issue because (for now) I copied the `awaitProcessing` function to my code and tested it out, and it worked fine! The video was successfully uploaded 😊
